
apiVersion: v1
kind: Pod
metadata:
  name: bppt-pod
  labels: 
    name: bppt-app-pod
    app: bppt-app-demo-kube   
spec: 
  containers:
   - name: wp-app
     image: harbor.jojonomic.io/bppt/api-gateway@sha256:795364089edb4ae1dc2fdaa0093a3adbf2b7a5cdcc779f5838f2a770131f1491
     ports:
     - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: bppt-service
  labels: 
    name: bppt-service
    app: bppt-app-demo-kube   
spec: 
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: bppt-app-pod
    app: bppt-app-demo-kube

