
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: apache-pod
    app: apache-pod-harbor
spec:
  containers:
  - name: apache-app
    image: harbor.jojonomic.io/infra/wordpress:latest
  imagePullSecrets:
  - name: regcred

