apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-app
    image: harbor.jojonomic.io/infra/mysql:5.6.37
  imagePullSecrets:
  - name: regcred

---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
spec:
  containers:
  - name: apache-app
    image: harbor.jojonomic.io/infra/php/apache:centos7
  imagePullSecrets:
  - name: regcred
