
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: apache-pod
    app: apache-pod-harbor
spec:
  containers:
  - name: apache-app
    image: harbor.jojonomic.io/infra/wordpress:latest
  imagePullSecrets:
  - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels: 
    name: apache-service
    app: apache-pod-harbor  
spec: 
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: apache-pod
    app: apache-pod-harbor


