
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
spec:
  containers:
  - name: apache-app
    image: docker pull harbor.jojonomic.io/infra/wordpress:latest
  imagePullSecrets:
  - name: regcred
