apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
  - name: mysql-app
    image: harbor.jojonomic.io/infra/mysql@sha256:6f603dccc80b540a0fc318c46a724440d3860fafb9a83f1658f577586a694254
  imagePullSecrets:
  - name: regcred

