
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels: 
    name: wordpress-app
    app: wordpress-app-demo-kube   
spec: 
  containers:
   - name: wp-app
     image: docker.io/falahalaf/wp-app
     ports:
     - containerPort: 80
