
apiVersion: v1
kind: Pod
metadata:
  name: apache-pod-harbor
  labels: 
    name: apache-pod-harbor
    app: wordpress-app-demo-harbor   
spec:
  containers:
  - name: apache-harbor
    image: harbor.jojonomic.io/infra/wordpress:latest
    ports:
     - containerPort: 80
  imagePullSecrets:
  - name: regcred

--- 

apiVersion: v1
kind: Service
metadata:
  name: harbor-service
  labels: 
    name: harbor-service
    app: wordpress-app-demo-harbor   
spec: 
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: apache-pod-harbor
    app: wordpress-app-demo-harbor


