
apiVersion: v1
kind: Pod
metadata:
  name: wordpress-pod
  labels: 
    name: wordpress-app-pod
    app: wordpress-app-demo-kube   
spec: 
  containers:
   - name: wp-app
     image: docker.io/falahalaf/wp-app
     ports:
     - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels: 
    name: wordpress-service
    app: wordpress-app-demo-kube   
spec: 
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    name: wordpress-app-pod
    app: wordpress-app-demo-kube

---

apiVersion: v1
kind: Pod
metadata:
  name: wp-mysql
  labels: 
    name: wordpress-mysql-pod
    app: wordpress-app-demo-kube   
spec: 
  containers:
   - name: wp-app
     image: docker.io/falahalaf/wp-mysql
     ports:
     - containerPort: 3306

--- 

apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
  labels: 
    name: w-mysql-service
    app: wordpress-app-demo-kube   
spec: 
  ports:
  - port: 3306
    targetPort: 3306
  type: LoadBalancer
  selector:
    name: wordpress-mysql-pod
    app: wordpress-app-demo-kube

